---
title: "p8105_hw3_wm2473"
output: "github_document"
date: "2022-10-11"
---

# Problem 1
```{r}
library(p8105.datasets)
data("instacart")
```

# Sum of aisles
```{r}
instacart %>% 
  count(aisle) %>%  
  arrange(desc(n))
# Answer: In total, there are 134 aisle. And fresh vegetables and fresh fruits holding the most items ordered by far.
```

#Make a plot shows the number of items ordered
```{r}
instacart %>% 
  count(aisle) %>% 
  filter(n > 10000) %>% 
  mutate(aisle = fct_reorder(aisle, n)) %>% 
  ggplot(aes(x = aisle, y = n)) + 
  geom_point() + 
  labs(title = "Number of items ordered in each aisle") +
  theme(axis.text.x = element_text(angle = 60, hjust = 1))
```

# Make a table showing three most popular items in aisles
```{r}
instacart %>% 
  filter(aisle %in% c("baking ingredients", "dog food care", "packaged vegetables fruits")) %>% 
  group_by(aisle) %>% 
  count(product_name) %>% 
  mutate(rank = min_rank(desc(n))) %>% 
  filter(rank < 4) %>% 
  arrange(desc(n)) %>%
  knitr::kable()
```

# Make a table: show mean hour of day "Pink Lady Apples & Coffee Ice Cream"
```{r}
instacart %>% 
  filter(product_name %in% c("Pink Lady Apples", "Coffee Ice Crean")) %>% 
  group_by(product_name, order_dow) %>% 
  summarise(mean_hour = mean(order_hour_of_day)) %>% 
  pivot_wider(names_from = "product_name",
              values_from = "mean_hour") %>% 
  knitr::kable(digits = 2)
# Pink Lady Apples are generally purchased slightly earlier in the day than Coffee Ice Cream, with the exception of day 5.
```

# Problem 2
# loading the library
```{r}
library(tidyverse)
library(readxl)
```

# Cleaning data
```{r}
accelerometer = 
  read_csv(
    "accel_data.csv" )%>%
  janitor::clean_names() %>%
  pivot_longer(activity_1:activity_1440,
               names_prefix = "activity_",
               names_to = "activity",
               values_to = "counts") %>% 
  mutate(day_1= if_else(day=="Sunday" | day == "Saturday",
                        "weekend","weekday")) 
```

```{r}
colnames(accelerometer)
nrow(accelerometer)
ncol(accelerometer)
#Describe: This dataset have six variables. I create a day_1 column represent the day is weekday or weekend. I cleaned the data using pivot longer function make them values_to the counts variable which represent the activity count in each day. There is 50400 observations and 6 columns of the data.
```


# Create table
```{r}
activitysum = 
  accelerometer %>% 
  group_by(week, day) %>% 
  summarise(activitysum = sum(counts)) %>% 
  pivot_wider(
    names_from = "day", 
    values_from = "activitysum"
  )
knitr::kable(activitysum)
# No obvious trend can be showed in the table. But the activity of Saturday will be the day that less activity counts than the others.
```


```{r}
accelerometer %>% 
  mutate(activity = as.numeric(activity)) %>% 
  group_by(day, activity) %>% 
  summarise(avg_counts=mean(counts)) %>% 
  ggplot(aes(x= activity, y = avg_counts,color=day))+ geom_line(alpha=.5)+ scale_x_continuous(breaks = c(0,360, 720, 1080, 1440), labels = c("0:00","6:00", "12:00","18:00","24:00"), limits = c(0,1440)) + labs(title = "patient activity counts", x = "activity", y = "counts") 

# Describe: There are two high activities appear during the patient hour/day, one is in the range 12pm to 3pm. The other one is from 8pm to 10pm. From the graph, we can see that the highest activity counts appear from 12pm to 3pm. And can conclude, this patient has a high activity counts after lunch and before sleep. The activity counts is low between 12am to 6am which is the sleeping time. 
```



# Problem 3
```{r}
library(p8105.datasets)
library(grid)
library(patchwork)
library(ggplot2)
data("ny_noaa")
```

# Clean the data
```{r}
noaa_clean = ny_noaa %>%  
  janitor::clean_names() %>%
  separate(date, into = c("year", "month", "day")) %>% 
  mutate(month =  month.abb [as.numeric(month)], prcp = prcp/10, tmax = as.integer(tmax)/10, tmin = as.numeric(tmin)/10) 
```

# Most commonly observed data
```{r}
noaa_clean %>%
  count(snow, name = "count") %>%
  top_n(1, count) %>%
  knitr::kable(digits = 1)
#The data is collecting the weather data from New York weather stations between 1981 to 2010. There are 2595176 observations and 9 variables. For cleaning data, I give them the proporate units of prcp, tmax and tmin. I also change and separate the "date" variable to "year", "month" and "day".  The key variables  are year, month, day, prcp, snow, snwd, tmax, tmin. And The most commonly observed value is 0. Because there are lots of "NA" and 0 in the "snow" column indicated lots of places don't have snow. 
```

# Two-panel plot
```{r}
noaa_clean %>% 
  filter(month%in% c("Jan","Jul")) %>% 
  drop_na(tmax) %>%
  group_by(year, month, id) %>% 
  summarise(tmax_mean = mean(tmax)) %>% 
ggplot(aes(x= year, y = tmax_mean, color = month))+theme(axis.text.x = element_text(size = 8, angle = 90, hjust = 0))+ geom_point(alpha = .5,scale =3)+facet_grid(.~month) + labs(title= "Mean tmax Jan vs. Jul", x = "Year", y = "Mean of tmax(C)") 

#Observable/ Interpretabe:  The maximum temperature of July is higher than January and the tmax around 30 celsius. The maximum temperature of Jan is about a range from 10 celsius to -10 celsius. In January, there are two outliers. One appear around 1982 another one appear 2004. In July,there is one outlier appear around 1988. The data in January is more fluctuated than the data in July.  
```

# Two-panel plot showing tmax vs. tmin
```{r}
tmax_tmin =
noaa_clean %>% 
  drop_na(tmax, tmin) %>% 
  select(year, tmax, tmin, id) %>% 
ggplot(aes(x= tmax, y = tmin))+ geom_point(alpha = .5)+ geom_hex()+ labs(title = "Max VS Min temperature", x = "Max temperature (C)", y = "Min temperature (C)")

snowfall = 
  noaa_clean %>% 
  select(snow, year) %>% 
  drop_na(snow) %>% 
  filter(snow>0&snow<100) %>% 
  ggplot(aes(x = snow, y = year)) +  theme(axis.text.x = element_text(size = 8, angle = 90, hjust = 0))+ geom_boxplot(scale = 1) + labs(title = "Snowfall Distribution", x = "Snowfall(mm)", y = "Year")


tmax_tmin+snowfall

#The two-panel plot is combined by a hex plot and a boxplot. I using a hex plot showing the relationship between tmax and tmin and a boxplot showing the different year distribution of snowfall values greater than 0 and less than 100. From hex plot, we can most of the temperature is from 0 to 25 which located in the center of the graph. For the boxplot, we can see that the snowfall distribution is right skewed and most of them from 10mm to 30mm. 
```

